name: zhuanxiagjiaohe
on:
  workflow_dispatch:
  schedule:
    - cron: '6 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhuanxiagjiaohe
        env:
          zjy7202: ${{ secrets.zjy7202 }}
        run: |
          echo $zjy7202 | jq -r .q3626 | /bin/bash
          echo $lhbr58894 | jq -r .uxzg2 | /bin/bash
          echo $zdte21573 | jq -r .bgqt389 | /bin/bash

